version: "3.5"
services:
  application:
    build:
      context: ./
      target: production
    environment:
      PORT: 3000
    ports:
    - "3000:3000"
  prometheus:
    image: prom/prometheus:v2.4.3
    ports:
    - "9090:9090"
  zipkin:
    image: openzipkin/zipkin:2.11.7
    ports:
    - "9411:9411"
